### PR TITLE
run local cross-env, not global cross-env

### PR DESCRIPTION
**Pull request by brunotag**
npx makes npm run the cross-env  present in node_modules instead of the one installed globally.

The advantage is: you don't need to have it installed globally :-)
And it also ensures it respects the version mentioned in the devDependencies.

### CODE REVIEW

**Comment by brunotag** [comment]
@ipearx I'm pretty confident this is fine.
It just ensures that the right version of `cross-env` is used when building

**Review by ipearx — COMMENTED** [review]
all good!

**Review by ipearx — COMMENTED** [review]
good

**Review by ipearx — APPROVED** [review]
actually approved

**Pull request merged**
